# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
# SPDX-License-Identifier: EUPL-1.2

# Application Properties
properties:
  apisecret: secret
  walletprovider:
    baseurl:
    wua-path: /wallet-provider/wallet-unit-attestation
  attributeattestation:
    baseurl: http://localhost:8088
    paths:
      post: /attestation
      get-by-id: /attestation
      get-by-user: /attestation/user

# Wallet Client Gateway Configuration
server:
  port: 8080
spring:
  application:
    name: wallet-client-gateway
  security:
    oauth2:
      client:
        registration: {}
        provider: {}

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
