# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
# SPDX-License-Identifier: EUPL-1.2

services:
  valkey:
    image: valkey/valkey:9.0.1@sha256:546304417feac0874c3dd576e0952c6bb8f06bb4093ea0c9ca303c73cf458f63
    ports:
      - "6379:6379"
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge
