# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

name: Ecosystem Integration Test

on:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: read
  packages: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-test:
    # Use the specific commit hash from the wallet-ecosystem repository for stability.
    uses: diggsweden/wallet-ecosystem/.github/workflows/reusable-integration.yml@69bb82d032235544d9cec8e09ab4407f5981f764
    with:
      service-name: wallet-client-gateway
      service-repo: ${{ github.repository }}
      service-ref: ${{ github.event.pull_request.head.sha || github.ref }}
