# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

name: Ecosystem Integration Test

on:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: read
  packages: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-test:
    uses: diggsweden/wallet-ecosystem/.github/workflows/reusable-integration.yml@cc44ac46629b998439db8c89649102392ddd6bc6 # main
    with:
      service-name: wallet-client-gateway
      service-repo: ${{ github.repository }}
      service-ref: ${{ github.event.pull_request.head.sha || github.ref }}
